#!/usr/bin/env bash
# configure web-02 to be identical to web-01


sudo apt-get update
sudo apt-get install -y nginx

cat <<EOT > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    add_header X-Served-By $hostname;
}
EOT

sudo systemctl restart nginx

sudo systemctl enable nginx
