#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.


sudo apt-get update
sudo apt-get install -y haproxy

cat <<EOT > /etc/haproxy/haproxy.cfg
global
    daemon

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOT

sudo systemctl restart haproxy

sudo systemctl enable haproxy
